"""
Outlook folder IDs — copied verbatim from Inbox Automation.json.

SOURCE_FOLDER_ID is where new mail lands and where the trigger watches.
LABEL_TO_FOLDER_ID maps each AI bucket label to its destination folder.
"""

SOURCE_FOLDER_ID = "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwAAAgEMAAAA"

LABEL_TO_FOLDER_ID = {
    "Addressed to me": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwZ1zJQAAAA==",
    "Urgent": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwZ1zJAAAAA==",
    "Normal priority": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwZ1zJgAAAA==",
    "Needs review": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwZ1zJwAAAA==",
    "Miscellaneous": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwxusDAAAAA==",
    "Promotions": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACwxusCwAAAA==",
    "BBG/Roxy": "AQMkADU3OGI0MWQwLWRjZWEtNDA2OS04MmE5LTY3MDM5MGVmYzVmZAAuAAADkrEgFtpjc0qhSL6htCeiCQEAIkOvDngUhkaW3dzeF0QyMwACw77UNQAAAA==",
}

ALLOWED_LABELS = list(LABEL_TO_FOLDER_ID.keys())

NEEDS_REVIEW_FOLDER_ID = LABEL_TO_FOLDER_ID["Needs review"]
